# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vayrT6XOlDu76kOziMt4pBAiFLW9cmkp
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import joblib
import streamlit
from sklearn.linear_model import LinearRegression
import joblib
import pandas
import numpy
import streamlit
import pandas
import scikit-learn

# Load dataset (pastikan file dataset.csv sudah di-upload ke Colab)
df = pd.read_csv('/content/dataset.csv')

# --- Start of fix ---
# Convert 'MW' column to numeric, coercing errors to NaN
df['MW'] = pd.to_numeric(df['MW'], errors='coerce')
# Drop rows where 'MW' is NaN (i.e., rows that contained non-numeric values)
df.dropna(subset=['MW'], inplace=True)
# --- End of fix ---

# Sesuaikan 'fitur' dan 'target' dengan nama kolom di dataset Anda
X = df[['MW']]  # Ganti dengan nama kolom independen (X)
y = df['MMBTUD']   # Ganti dengan nama kolom dependen (Y)

# Bagi data dan latih model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)

# Simpan model ke file pickle
joblib.dump(model, 'model_regresi.pkl')
print("Model berhasil disimpan sebagai model_regresi.pkl")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import joblib
# import numpy as np
# 
# # Load model yang sudah dilatih
# model = joblib.load('model_regresi.pkl')
# 
# st.title('GAS CONSUMPTION GT BLOK 3 PLTGU GRATI')
# st.write('Beban Gas Turbine.')
# 
# # Input nilai dari user
# nilai_x = st.number_input('Masukkan Beban MW (X):', value=0.0)
# 
# if st.button('Calculate by Didik'):
#     # Lakukan prediksi
#     prediksi = model.predict(np.array([[nilai_x]]))
#     st.success(f'GAS CONSUMPTION MMBTUD (Y): {prediksi[0]:.2f}')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# scikit-learn
# joblib
# pandas
# numpy
#streamlit
#pandas
#scikit-learn
